apiVersion: v1
kind: Service
metadata:
  name: golang-gin-kubernetes-boilerplate
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: golang-gin-kubernetes-boilerplate 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-gin-kubernetes-boilerplate
  labels:
    app: golang-gin-kubernetes-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-gin-kubernetes-boilerplate
  template:
    metadata:
      labels:
        app: golang-gin-kubernetes-boilerplate
    spec:
      containers:
      - name: golang-gin-kubernetes-boilerplate
        image: golang-gin-kubernetes-boilerplate
        ports:
        - containerPort: 8080